### ISSUE TITLE
org.eclipse.microprofile.reactive.streams.ReactiveStreamsFactoryResolver#loadFromSpi does not work

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-reactive-streams-operators#111]
org.eclipse.microprofile.reactive.streams.ReactiveStreamsFactoryResolver#loadFromSpi starts by the parent which almost never works (EE, OSGi) except in flat classpath cases or it prevents the users to provides its own impl. Sticking to the TCCL is likely the only relevant default for such an embeddable spec

**Comment by cescoffier** [comment]
We use the same approach as MicroProfile Config.

**Comment by jroper** [comment]
Doesn't it search parent first anyway? The `ServiceLoader` iterator uses the the ordering from `ClassLoader.getResources`, which is parent first. Looking at the original issue that introduced this change, https://github.com/eclipse/microprofile-config/issues/20, it seems that the reason the manual parent first search was done was to avoid situations where multiple services were returned. But it doesn't actually solve the problem since multiple services could still be found - I don't think it makes sense to fail if multiple are found on the classpath, instead, I think we should just take the first one. This one will come from a parent classloader if defined there, unless the classloader in use implements a different strategy in `getResources`, which may well be the case in OSGi and is the case in wars.

**Comment by rmannibucau** [comment]
Nop, it search respecting the context in which it is called. If this classloader is not parent first then it will search another way and this is the point of this ticket. Parent first is only the default in the jvm, there are multiple other impl in the nature now ;)

**Comment by Emily-Jiang** [comment]
I believe this is fixed as the current loadfromSpi does look for parent classloader any more. I'm going to close this one. Please reopen if you think otherwise.
